name: jivanand
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  # COMMON
  nb_utils: ^7.0.6
  google_fonts: ^6.2.1
  html: ^0.15.4
  http: ^1.2.2
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  #speech_to_text: ^7.0.0


  # FIREBASE
  firebase_core: ^3.6.0
  firebase_crashlytics: ^4.1.3
  #firebase_auth: ^5.3.1
  #firebase_storage: ^12.3.3
  #cloud_firestore: ^5.4.4
  #firebase_pagination: ^4.0.1


  # FIREBASE MESSAGING
  #firebase_messaging: ^15.1.3
  #flutter_local_notifications: ^17.2.3

  # STATE MANAGEMENT
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  # ICON
  flutter_vector_icons: ^2.0.0
  flutter_svg: ^2.0.10+1

  # IMAGE
  image_picker: ^1.1.2
  photo_view: ^0.15.0
  lottie: ^3.1.2

  # OTHER
  flutter_custom_tabs: ^2.1.0
  permission_handler: ^11.3.1
  flutter_html: ^3.0.0-beta.2
  path_provider: ^2.1.4

  device_info_plus: ^11.1.1
  platform_info: ^5.0.0
  dio: ^5.7.0
  #media_scanner: ^2.1.0
  sleek_circular_slider: ^2.0.1
  sqflite: ^2.4.1

  webview_flutter: ^4.9.0
  file_picker: ^8.1.2
  flutter_image_compress: ^2.3.0
  badges: ^3.1.2

  carousel_slider: ^5.0.0
  #share_plus: ^10.0.3
  share_plus: ^7.2.1
  photo_manager: ^3.6.2
  change_app_package_name: ^1.4.0

  dotted_border: ^2.1.0
  pdf: ^3.10.4
  printing: ^5.13.2
  image_cropper: ^5.0.1

  flutter_localizations:
    sdk: flutter

  path: any
  permission_handler_platform_interface: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13
  mobx_codegen: ^2.6.1
  flutter_lints: ^4.0.0
  #flutter_gen_runner: ^5.4.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:
  uses-material-design: true
  assets:
    - assets/icon.png
    - assets/41340_AANGAN_thumbnail.webp
    - assets/icons/
    - assets/
    - assets/images/
    - assets/lottie/
    - assets/app_icon/
    - assets/dresoul/
    - assets/jivanand/
    - assets/banner/
    - assets/json/
    - assets/font/
    - assets/font/Aakar.ttf
    - assets/Roboto-Regular.ttf
    - assets/Roboto-Black.ttf
    - assets/Roboto-Bold.ttf
    - assets/Roboto-Medium.ttf
  fonts:
    - family: Aakar
      fonts:
        - asset: assets/font/Aakar.ttf